# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

exclude_paths:
  - ".github"
  - ".vscode"
  - "LICENSE"
  - "README.md"
  - "data/**/*"
  - "models/**/*"
  - "schemas/**/*"
  - "tests/**/*"
  - "postman_collections/**/*"
  - "main.py"
