# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 10%
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 10%

flags:
  unit:
    paths:
      - "services/"
      - "routes/"
    carryforward: true

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"

  individual_components:
    - component_id: services
      name: Services
      paths:
        - "services/"
    - component_id: routes
      name: Routes
      paths:
        - "routes/"

comment:
  layout: "header, diff, flags, components"

ignore:
  - "assets/**/*"
  - "data/**/*"
  - "models/**/*"
  - "postman_collections/**/*"
  - "schemas/**/*"
  - "tests/**/*"
  - "**/*.yml"
  - "**/*.json"
  - "**/*.txt"
  - "**/__pycache__/"
  - "**/*.pyc"
  - "LICENSE"
  - "main.py"
  - "README.md"
