# https://docs.codecov.com/docs/codecov-yaml

ignore:
  - "data"
  - "models"
  - "schemas"
  - "tests"
  - "postman_collections"
  - "main.py"

coverage:
  status:
    project:
      routes:
        paths:
          - "routes"
      services:
        paths:
          - "services"
    patch:
      default:
        informational: true
